---
- hosts: all
  vars_files:
    - variable-apt-v.yml
  become: yes
  become_method: sudo
  tasks:
  - name: apt-get update
    command: "apt-get {{upd}}"
  - name: apt-get check all packages installed
    command: "{{dpkg}}"
