---
- hosts: all
  vars_files:
    - var-mongo.yml
  become: yes
  become_method: sudo
  tasks:

  - name: Backup
    shell: "{{backup}} -d {{database}} -o {{bkppath}}"
    args:
      warn: false # set warn=false to prevent warning
    register: command_output
  - debug: msg="{{command_output.stdout}}"
