---
- hosts: all
  vars_files:
    - variable_test.yml
  become: yes
  become_method: sudo
  tasks:
  - name: Create user 
    user: name={{user}} comment="The Deploy user" group={{group}} shell=/bin/bash
