---
- hosts: all
  vars_files:
    - var-del-file.yml
  become: yes
  become_method: sudo
  tasks:

  - name: delete file
    shell: "rm /root/service-version.txt"
    args:
      warn: false # set warn=false to prevent warning
    register: command_output
  - debug: msg="{{command_output.stdout}}"
